# Generated by Django 5.1.15 on 2026-03-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('speaker', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='recordings/')),
                ('recording_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
