# Generated by Django 6.0.3 on 2026-03-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(blank=True, default='', upload_to='recordings/'),
        ),
    ]
