# Generated by Django 6.0.3 on 2026-03-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_alter_recording_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
