# Generated by Django 5.1.15 on 2026-03-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_recording_archived_at_recording_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ['-uploaded_at', '-pk']},
        ),
    ]
