# Generated by Django 5.1.15 on 2026-03-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('reflection', 'Spiritual Reflection'), ('motivation', 'Motivation'), ('advice', 'Advice'), ('dua', "Du'a & Dhikr"), ('reminder', 'Daily Reminder')], default='reflection', max_length=20)),
                ('published_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
