# Generated by Django 6.0.3 on 2026-03-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('writings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writing',
            name='category',
        ),
        migrations.AddField(
            model_name='writing',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
